export const projects = [
  // {
  //   name: '',
  //   desc: '',
  //   github: '',
  //   tags: ['TAGS'],
  // },
  {
    name: 'Personal Website',
    desc: "My personal website is a project in itself. This site was built using React, React Router, and other technologies using information learned from The Odin Project's React course",
    github: 'https://github.com/jamesspearsv/personal-website',
    tags: ['React', 'Javascript', 'Sass', 'Vite'],
  },
  {
    name: 'LibStats',
    desc: 'LibStats is a basic library reference statistics collection tool built specifically for use in my public library. The tool is built on Python and Django and utilizes Docker for deployment.',
    github: 'https://github.com/jamesspearsv/libstats',
    tags: ['Python', 'Django', 'Docker', 'Bootstrap'],
  },
  {
    name: 'Shopping Cart',
    desc: "This is my solution to The Odin Project's React course shopping cart project. This project was built using React fundamentals including state management, data fetching with useEffect, routing with React-Router, and CSS modules",
    github: 'https://github.com/jamesspearsv/shopping-cart-project',
    live: 'https://shopping-cart-project-1di.pages.dev/',
    tags: ['Javascript', 'React', 'Vite'],
  },
  {
    name: 'CV Builder',
    desc: "This is my solution to The Odin Project's React course CV Builder project. This project is built using basic React principles including state, components",
    github: 'https://github.com/jamesspearsv/cv-builder',
    live: 'https://cv.jspears.me',
    tags: ['Javascript', 'React', 'Vite'],
  },
  {
    name: 'Memory Game',
    desc: "This is my solution to The Odin Project's React course Memory Game project. This project is built using React and demonstrates the useEffect hook in addition to other basic React principles.",
    github: 'https://github.com/jamesspearsv/memory-game-top',
    live: 'https://memory.jspears.me',
    tags: ['Javascript', 'React', 'Vite'],
  },
  {
    name: 'To-Do App',
    desc: "This is my solution to The Odin Project's Javascript course To-Do App project. This project is built using vanilla Javascript principles including modules and factory functions and web APIs including local storage.",
    github: 'https://github.com/jamesspearsv/todo-list',
    live: 'https://jamesspearsv.github.io/todo-list/',
    tags: ['Javascript', 'HTML & CSS', 'Webpack'],
  },
  {
    name: 'Age Calculator',
    desc: "This is my solution to Frontend Mentor's Age Calculator challenge. This project was built using basic web technologies including semantic HTML, CSS, and Javascript.",
    github: 'https://github.com/jamesspearsv/age-calculator',
    live: 'https://jamesspearsv.github.io/age-calculator/',
    tags: ['Javascript', 'HTML & CSS', 'Webpack'],
  },
  {
    name: 'Tic Tac Toe Game',
    desc: "This is my solution the Odin Project's Javascript course Tic Tac Toe project. This project was built using fundamental Javascript principles including modules, functions, and factory functions.",
    github: 'https://github.com/jamesspearsv/tictactoe-project',
    live: 'https://jamesspearsv.github.io/tictactoe-project/',
    tags: ['Javascript', 'HTML & CSS', 'Webpack'],
  },
];
